{% set name = "ftputil" %}
{% set version = "5.0.2" %}
{% set md5 = "b233e48309947e123aacf7ee817534d5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - ftputil
  commands:
    - python -c "from ftputil import FTPHost"

about:
  home: http://ftputil.sschwarzer.net/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: High-level FTP client library (virtual file system and more)

  description: |
    ftputil is a high-level FTP client library for the Python programming
    language. ftputil implements a virtual file system for accessing FTP
    servers, that is, it can generate file-like objects for remote files.
    The library supports many functions similar to those in the os, os.path
    and shutil modules. ftputil has convenience functions for conditional
    uploads and downloads, and handles FTP clients and servers in different
    timezones.
  doc_url: http://ftputil.sschwarzer.net/trac/wiki/Documentation

extra:
  recipe-maintainers:
    - edisongustavo
    - nicoddemus
    - tadeu
