travis:
  secure:
    BINSTAR_TOKEN: Am4KE+CIYr7w/UTVlYSMim54fkWQmemHaUjJfVGOLnnuSu1Q0l4hrP/vkJ75G+edIBeGipuaLflNf1RFUFw9tZz8IwTajELXowPAWBmurAdL5pSkA2Zgkmwlnq8mRh9EArVxtqP9NW1Bu6/R0bCz7pc5H5vdWofWyvzy2e2Lat6vABMGhoEtziQQtmLyUWGDu/MDLDvxrVNzRQfGggl8P0iwrmrWH0BhbKvzsU9R0gXzhKlfTUeRr03pynn/0aF2uYOFD26meYLOpeOCfh5N/SVXhJ5LODHWOd+veWXyYTrtsUMeKkBvMiOvmgDMq9zefl/Wea414Cfrm7uSesCVCfmiZSGuHGE0tpTm6Wc51H7vh2bK1aL0YYvZ26rBDR4a5CC/ntbBYYyfocJ5dGtbzySdUMAT6IXOy5VZsjhei7rw07Xoc0+noN7vXO8F4E0f+2ej8k0FhhWR3FDecF5izcrm4Oj7hYjWoL6euXq0K5z+I7CNAMMU6UgJtYMnvIKJTEqzgajooW6wdMMtoQP+wtAosnVR1CEZfPYHTtWiSMV7kCK1BSyT1i81k0fsI9cSTSOLcJYLN633bnJgG2fp+DpWuXsc0ZnvSTM7NBXDhBi6i6WTklY/hxxokO6d/Ajbz2xJUSPC46DT9AlZ+KJvXY65cNNZMAq1l5djw9kQ0ag=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
