travis:
  secure:
    BINSTAR_TOKEN: nhEzoJzM7uOC4BupMlq3k9iPrktGvxtrZaUNPqHCeBri4nLb0+1ggAM0exhnxxAOXLsHoqTS62tLtyM0ab2+3dVj7W2TIKstKJunwUT6syqN3lhTguzskHz9bEOgVL6D/oIgEzOOBp7HSxbtSlJuWtRDpdZ3Z1QsE2LpebCstRaLaR9jfAym+FkqSDXfB1jRmk8RkIu7IDAFp8O0wMCARWoScUSDnnbPRqaIxIgbURWxzXihs+ElG6wtBQILsae5ZIi4QBhGvU8HFx/lyDThu0MSFHdFUyJkmp9YaIDcw9T9b8H6dGDyyFEDaVr/kUG3OvNswso16Iw14+tgBVTZnZjAjnHTlsU8PFymB5oyDn8WNGIjBCofIOnRjXeX94YbANXYcTsx8rO57cXTgzjalCg9HSreZmem3suI6XPL5JWBrLj9Oh6Ij6G28LYFmsxUnmZMJ0yjpRGMwFI4ON4GNn1ikJlL9t6eSjJe2b2pbrS2DOYDxeEVQrEqqoNDVMxpoXjVCdfXDQZG+tqwkL3AOZegvtXKn8k28EHZFGXj8RNqX2/W8VnGqKIRHtuOm58BZLrYZO17ATaDm18htR4bVBuUWixSufQGP6OhAnt1wqxK7Zm+lH7Zcw3SfnbbVSxlpWh05ZJFmq5G0I6XIGUHCfqJ8wSuFOSFISs6B1UkATA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
